# Generated by Django 4.1.5 on 2023-01-03 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_alug_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='propduct_name',
            new_name='product_name',
        ),
    ]
