# Generated by Django 4.1.5 on 2023-01-03 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='catageory_name',
            new_name='category_name',
        ),
    ]
